### NumPy练习题1


In [2]:
import numpy as np

1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [5]:
n = np.zeros(10, dtype=np.int32)
n[4] = 1
n

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

2、创建一个元素为从10到49的ndarray对象

In [6]:
n = np.arange(10, 50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3、将第2题的所有元素位置反转

In [7]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [9]:
n = np.random.random(size=(10, 10))
display(n, np.max(n), np.min(n))


array([[0.96135371, 0.14455258, 0.22354549, 0.81478348, 0.89393681,
        0.50993162, 0.63072777, 0.09244888, 0.62330528, 0.78905501],
       [0.16244508, 0.13701458, 0.96396972, 0.64922613, 0.77373916,
        0.27916214, 0.36154591, 0.88149112, 0.59742808, 0.66880004],
       [0.12870959, 0.55754251, 0.37907791, 0.15612625, 0.60769765,
        0.22175677, 0.11573754, 0.14566995, 0.39805102, 0.35539319],
       [0.8618085 , 0.74593232, 0.30184443, 0.93464549, 0.28681501,
        0.9550637 , 0.96080163, 0.33305314, 0.16866638, 0.15584723],
       [0.16147302, 0.44501245, 0.77877019, 0.31660648, 0.15587822,
        0.33134151, 0.14292743, 0.01687672, 0.60362937, 0.76167196],
       [0.38796036, 0.31043644, 0.71905926, 0.59779447, 0.43943092,
        0.56179544, 0.99318974, 0.3209097 , 0.51499959, 0.91772047],
       [0.98012762, 0.80091495, 0.75798787, 0.87244328, 0.87223948,
        0.0832874 , 0.87782243, 0.17881538, 0.64829289, 0.97870505],
       [0.04817166, 0.24074386, 0.6433087

0.9931897428663227

0.01687672203518087

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [14]:
n = np.zeros((10, 10), dtype=np.int16)
n[[0, -1]] = 1
n[:, [0, -1]] = 1
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

In [16]:
n = np.ones((10, 10), dtype=np.int16)
n[1:-1, 1:-1] = 0
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int16)

6、创建一个每一行都是从0到4的5*5矩阵

In [20]:
l = [0, 1, 2, 3, 4]
n = np.array(l*5).reshape((5, 5))
n

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [21]:
n = np.linspace(0, 1, 12)
n

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序


In [24]:
n = np.random.randint(0, 10, 10)
n.sort()
n[::-1]

array([9, 8, 8, 8, 7, 7, 7, 4, 2, 1])

9、创建一个长度为10的随机数组并将最大值替换为0


In [30]:
n = np.random.randint(0, 10, size=10)
display(n)

array([8, 7, 3, 2, 7, 8, 0, 8, 4, 6])

In [36]:
max1 = np.max(n)
max1

# 所有最大值对应的索引
max_indexs = np.argwhere(n==max1).reshape(-1)

n[max_indexs] = 0
n

array([0, 7, 3, 2, 7, 0, 0, 0, 4, 6])